CREATE DATABASE IF NOT EXISTS DB1 CHARSET=utf8;
USE DB1;

CREATE TABLE IF NOT EXISTS person(
p_id INT(11) NOT NULL AUTO_INCREMENT , 
name VARCHAR(50) NULL,
surname VARCHAR(50) NULL,
username VARCHAR(50) NOT NULL,
password VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL,
phone_number BIGINT NULL,
birthdate DATE NOT NULL,
authorization ENUM('a','b') DEFAULT 'a' NOT NULL,
gender ENUM('m','f') NOT NULL,
PRIMARY KEY (p_id),
UNIQUE(username)
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS user(
u_id INT(11) NOT NULL,
sign_up_date DATETIME NOT NULL,
PRIMARY KEY (u_id),
CONSTRAINT per_us
FOREIGN KEY (u_id) REFERENCES person(p_id)
ON DELETE CASCADE ON UPDATE CASCADE
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS administrator(
a_id INT(11) NOT NULL,
bio TEXT NULL,
PRIMARY KEY(a_id),
CONSTRAINT per_adm
FOREIGN KEY (a_id) REFERENCES person(p_id)
ON DELETE CASCADE ON UPDATE CASCADE
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS category(
c_id INT(11) NOT NULL AUTO_INCREMENT ,
c_name VARCHAR(50) NOT NULL,
c_description MEDIUMTEXT NOT NULL,
PRIMARY KEY(c_id),
UNIQUE(c_name)
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS report(
state ENUM('s','u') DEFAULT 'u' NOT NULL,
gps VARCHAR(100) NOT NULL,
r_id INT(11) NOT NULL AUTO_INCREMENT,
r_description MEDIUMTEXT NOT NULL,
reg_date DATETIME NOT NULL,
solv_date DATETIME NULL,
solved_time FLOAT NULL,
a_comments TEXT NULL,
us_id INT(11)NOT NULL,
ad_id INT(11) NOT NULL,
categ_id INT(11) NOT NULL,
PRIMARY KEY (r_id), 
CONSTRAINT rep_us
FOREIGN KEY (us_id) REFERENCES user(u_id)
ON DELETE RESTRICT ON UPDATE CASCADE, 
CONSTRAINT rep_adm
FOREIGN KEY (ad_id) REFERENCES administrator(a_id)
ON DELETE RESTRICT ON UPDATE CASCADE,
CONSTRAINT cat
FOREIGN KEY (categ_id) REFERENCES category(c_id)
ON DELETE RESTRICT ON UPDATE CASCADE 
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS us_ad(
user_id INT(11) NOT NULL,
admin_id INT(11) NOT NULL,
PRIMARY KEY(user_id,admin_id),
CONSTRAINT xri
FOREIGN KEY (user_id) REFERENCES user(u_id)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT diax
FOREIGN KEY (admin_id) REFERENCES administrator(a_id)
ON DELETE CASCADE ON UPDATE CASCADE 
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS ad_cat(
adm_id INT(11) NOT NULL,
cat_id INT(11) NOT NULL,
PRIMARY KEY(adm_id,cat_id),
CONSTRAINT diaxiris
FOREIGN KEY (adm_id) REFERENCES administrator(a_id)
ON DELETE CASCADE ON UPDATE CASCADE,
CONSTRAINT katig
FOREIGN KEY (cat_id) REFERENCES category(c_id)
ON DELETE CASCADE ON UPDATE CASCADE 
)Engine=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS images(
rep_id INT(11) NOT NULL,
photo VARCHAR(255) NULL,
PRIMARY KEY(rep_id,photo),
CONSTRAINT rep_img
FOREIGN KEY (rep_id) REFERENCES report(r_id)
ON DELETE CASCADE ON UPDATE CASCADE
)Engine=InnoDB DEFAULT CHARSET=utf8;